' (c) The copyright relating to this work is owned jointly by the Crown,
' Met Office and NERC 2014. However, it has been created with the help of the
' GungHo Consortium, whose members are identified at
' https://puma.nerc.ac.uk/trac/GungHo/wiki

class gencube_ps_mod::gencube_ps_type {
  -ndivs: integer
  -nsmooth: integer
  -cell_next: integer[::] <<allocatable>>
  -verts_on_cell: integer[::] <<allocatable>>
  -edges_on_cell: integer[::] <<allocatable>>
  -verts_on_edge: integer[::] <<allocatable>>
  -vert_coords: real[::] <<allocatable>>
  +<<create>>gencube_ps_constructor( <<in>> ndivs: integer, <<in>> nsmooth: integer ): gencube_ps_type
  +calc_adjacency ( <<out>> cell_next:integer[::] <<allocatable>> )
  +calc_face_to_vert ( <<out>> verts_on_cell:integer[::] <<allocatable>> )
  +calc_edges( <<out>> edges_on_cell: integer[::] <<allocatable>>,
  <<out>> verts_on_edge: integer[::] <<allocatable>> )
  +calc_coords( <<out>> vert_coords: real[::] <<allocatable>> )
  +get_dimensions( <<out>> num_nodes: integer, <<out>> num_edges: integer, <<out>> num_faces: integer, <<out>> num_nodes_per_face: integer, <<out>> num_edges_per_face: integer, <<out>> num_nodes_per_edge: integer )
  +get_coordinates(( <<out>> node_coordinates: real[::] )
  +get_connectivity( <<out>> face_node_connectivity: integer[::], <<out>> edge_node_connectivity: integer[::], <<out>> face_edge_connectivity: integer[::], <<out>> face_face_connectivity: integer[::] )
  +generate()
  +write_mesh()
  +orient_lfric()
  +smooth()

}

note "gencube_ps_type used as\ninput for set_by_generator()" as N1

gencube_ps_mod::gencube_ps_type -up-|> ugrid_generator_mod::ugrid_generator_type

gencube_ps_mod::gencube_ps_type .up. N1
N1 .up. ugrid_2d_mod::ugrid_2d_type
