' (c) The copyright relating to this work is owned jointly by the Crown,
' Met Office and NERC 2014. However, it has been created with the help of the
' GungHo Consortium, whose members are identified at
' https://puma.nerc.ac.uk/trac/GungHo/wiki

@startuml

!include look.iuml
!include setup/mesh_collection_mod.iuml
!include setup/global_mesh_collection_mod.iuml
class mesh_mod::mesh_type {
}
class global_mesh_mod::global_mesh_type {
}

global_mesh_collection_mod::global_mesh_collection_type o-> "*" global_mesh_mod::global_mesh_type
mesh_collection_mod::mesh_collection_type o-> "*" mesh_mod::mesh_type

@enduml
