@startuml

!include look.iuml
!include setup/mesh_mod.iuml
!include setup/partition_mod.iuml
!include setup/global_mesh_mod.iuml
!include setup/mesh_collection_mod.iuml

linked_list_data_mod::linked_list_data_type <|-- mesh_mod::mesh_type

@enduml
