#!/bin/sh

# tweak_iodef: resolve env symbols in iodef file before rose suite starts.

iodef=iodef.xml
case $# in 
0) ;;
1) iodef=$1 ;;
*) echo 'usage: tweak_iodef [iodef_file]' 1>&2; exit 2
esac

set -e
temp_file=$(mktemp)
trap 'rm -f $temp_file; exit 1' INT TERM EXIT
rose env-cat $iodef -o $temp_file
trap '' INT TERM EXIT
mv $temp_file $iodef
