' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

@startuml

!include look.iuml

!include inventory/inventory_by_mesh_mod.iuml
!include inventory/inventory_by_local_mesh_mod.iuml
!include inventory/id_abstract_pair_mod.iuml
!include inventory/id_integer_pair_mod.iuml
!include inventory/id_integer_array_pair_mod.iuml
!include inventory/id_integer_field_pair_mod.iuml
!include inventory/id_integer_field_array_pair_mod.iuml
!include inventory/id_r32_field_array_pair_mod.iuml
!include inventory/id_r32_field_pair_mod.iuml
!include inventory/id_r32_operator_pair_mod.iuml
!include inventory/id_r64_field_pair_mod.iuml
!include inventory/id_r64_field_array_pair_mod.iuml
!include inventory/id_r64_operator_pair_mod.iuml

inventory_by_mesh_mod::inventory_by_mesh_type o-> "*" id_abstract_pair_mod::id_abstract_pair_type
inventory_by_local_mesh_mod::inventory_by_local_mesh_type o-> "*" id_abstract_pair_mod::id_abstract_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_integer_pair_mod::id_integer_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_integer_array_pair_mod::id_integer_array_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_integer_field_pair_mod::id_integer_field_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_integer_field_array_pair_mod::id_integer_field_array_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r32_field_pair_mod::id_r32_field_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r32_field_array_pair_mod::id_r32_field_array_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r32_operator_pair_mod::id_r32_operator_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r64_field_pair_mod::id_r64_field_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r64_field_array_pair_mod::id_r64_field_array_pair_type
id_abstract_pair_mod::id_abstract_pair_type ^- id_r64_operator_pair_mod::id_r64_operator_pair_type

@enduml
