' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

abstract class id_abstract_pair_mod::id_abstract_pair_type {
  -id_: integer

  +get_id( ) : integer
  +set_id( <<in>> id: integer ) :
}
