' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_integer_array_pair_mod::id_integer_array_pair_type {
  -numbers_: integer

  +initialise( <<in>> numbers: integer, <<in>> id: integer ) :
  +get_integer_array( ) : integer
}
