' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_integer_pair_mod::id_integer_pair_type {
  -number_: integer

  +initialise( <<in>> number: integer, <<in>> id: integer ) :
  +get_integer( ) : integer
}
