' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_r64_operator_pair_mod::id_r64_operator_pair_type {
  -operator_: operator_r64_type

  +initialise( <<in>> operator_in: operator_r64_type, <<in>> id: integer ) :
  +get_operator( ) : operator_r64_type
}
