' (c) The copyright relating to this work is owned jointly by the Crown,
' Met Office and NERC 2014. However, it has been created with the help of the
' GungHo Consortium, whose members are identified at
' https://puma.nerc.ac.uk/trac/GungHo/wiki

class function_space_chain_mod::function_space_chain_type{

+<<create>>  function_space_chain_constructor(): function_space_chain_type
+<<destroy>> function_space_chain_destructor()
+clear()

+add(<in>function_space:<<function_space_type,pointer>>)
+get_start(): function_space_type <<pointer>>
+get_next(): function_space_type <<pointer>>
+get_previous(): function_space_type <<pointer>>
}

function_space_chain_mod::function_space_chain_type -> linked_list_mod::linked_list_type : <size:8>-function_space_chain_list
function_space_pointer_mod::function_space_pointer_type -|> linked_list_data_mod::linked_list_data_type
