' (c) The copyright relating to this work is owned jointly by the Crown,
' Met Office and NERC 2014. However, it has been created with the help of the
' GungHo Consortium, whose members are identified at
' https://puma.nerc.ac.uk/trac/GungHo/wiki

class function_space_mod::function_space_type {
    -basis_index: integer[::] <<allocatable>>
    -basis_order: integer[::] <<allocatable>>
    -basis_vector: real[::] <<allocatable>>
    -basis_x: real[:::] <<allocatable>>
    -dim_space: integer
    -dim_space_diff: integer
    -distgrid: ESMF_DistGrid
    -dofmap_list: linked_list
    -dof_on_vert_boundary: integer[::]
    -element_order: integer
    -fs: integer
    -fs_order: integer
    -global_dof_id: integer[] <<allocatable>>
    -haloHandle: ESMF_RouteHandle[] <<allocatable>>
    -last_dof_annexed: integer
    -last_dof_halo: integer[] <<allocatable>>
    -last_dof_owned: integer
    -master_dofmap: master_dofmap
    -mesh: mesh_type <<pointer>>
    -ndof_cell: integer
    -ndof_edge: integer
    -ndof_exterior: integer
    -ndof_face: integer
    -ndof_glob: integer
    -ndof_interior: integer
    -ndof_vert: integer
    -ndof_vol: integer
    -nodal_coords: real[::] <<allocatable>>

    <<create>>+fs_constructor( <<in>>mesh_id: integer, <<in>>element_order: integer, <<in>>dynamo_fs: integer ) : function_space_type <<pointer>>
    <<destroy>>+function_space_destructor()

    +clear()
    +compute_basis_function( <<out>>basis: real[::::], <<in>>ndf: integer, <<in>>qp_h: integer, <<in>>qp_v: integer, <<in>>x_qp: real[::], <<in>>z_qp[] )
    +compute_diff_basis_function( <<out>>dbasis: real[::::], <<in>>ndf: integer, <<in>>qp_h: integer, <<in>>qp_v: integer, <<in>>x_qp::real[::], <<in>>z_qp: real[] )
    +evaluate_function( <<in>> func_to_call: integer, <<in>> df: integer, <<in>> xi: real(:) ) : real[:]
    +evaluate_basis( <<in>>df: integer, <<in>>xi: real[3] ) : real[]
    +evaluate_diff_basis( <<in>>df: integer, <<in>>xi: real[3] ) : real[]
    +get_boundary_dofs() : integer <<pointer>>
    +get_cell_dofmap( <<in>>cell_lid: integer ) : integer[] <<pointer>>
    +get_colours( <<out>>ncolours: integer, <<out>>ncells_per_colour: integer[] <<pointer>>, <<out>>colour_map: integer[::] <<pointer>> )
    +get_dim_space() : integer
    +get_dim_space_diff() : integer
    +get_distgrid(): ESMF_DistGrid
    +get_element_order(): integer
    +get_fs_order() : integer
    +get_global_dof_id( <<inout>>global_dof_id: integer[] )
    +get_haloHandle( <<in>>depth: integer ): ESMF_RouteHandle
    +get_last_dof_halo() : integer
    +get_last_dof_owned() : integer
    +get_mesh(): mesh_type <<pointer>>
    +get_mesh_id(): integer
    +get_ncell() : integer
    +get_ncolours(): integer
    +get_ndf() : integer
    +get_nodes() : real[::] <<pointer>>
    +get_nlayers() : integer
    +get_stencil_dofmap( <<in>>stencil_shape: integer, <<in>>stencil_size: integer ) : stencil_dofmap <<pointer>>
    +get_undf() : integer
    +set_colours()
    +which() : integer
}

evaluate_function_mod::evaluate_function_type <|-- function_space_mod::function_space_type
